language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
notifications:
  email:
    recipients:
    - nk8smg@hotmail.com
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-mutator-graphite.gemspec
- gem install sensu-mutator-graphite-*.gem
deploy:
  provider: rubygems
  gem: sensu-mutator-graphite
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    repo: Kidinicol/sensu-mutator-graphite
